apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ybm2i-devops-app
  name: ybm2i-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ybm2i-devops-app
  strategy: {}
  template:
    metadata:
      labels:
        app: ybm2i-devops-app
    spec:
      volumes:
      - name: vol
        emptyDir: {}
      serviceAccountName: default
      containers:
      - image: replace
        name: ybm2i-devops-app-container
        volumeMounts:
        - mountPath: /tmp
          name: vol
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ybm2i-devops-app
  name: ybm2i-devops-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ybm2i-devops-app
  type: NodePort
